version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  test:
    build:
      context: ./frontend
    command: ["npm", "test"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
